server:
  port: 8082 
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalogdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
