server:
  port: 8082 
  
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catalogdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# spring:
#   jpa:
#     defer-datasource-initialization: true
#     hibernate:
#       ddl-auto: create-drop

#   datasource:
#     driverClassName: org.h2.Driver
#     url: jdbc:h2:mem:db;DB_CLOSE_DELAY=1;
#     username: sa
#     password: sa