server:
  port : 8081
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=1;
    username: sa
    password: sa
    
  sql:
    init:
      dataLocations: classPath:/movie-service.sql