server:
  port : 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: seriedb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

